// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for TransactionDataRequestOperation.
const (
	Credit TransactionDataRequestOperation = "credit"
	Debit  TransactionDataRequestOperation = "debit"
)

// The country code from ISO 3166 find more at https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
type CountryCode = string

// The currency code from ISO 4217 find more at https://en.wikipedia.org/wiki/ISO_4217
type CurrencyCode = string

// GenericError defines model for generic-error.
type GenericError struct {
	Code        *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
}

// Id defines model for id.
type Id = string

// RequestCancellation defines model for request-cancellation.
type RequestCancellation struct {
	AcquirerCode      string `json:"acquirer_code"`
	AuthorizationCode string `json:"authorization_code"`

	// The country code from ISO 3166 find more at https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
	CountryCode CountryCode `json:"country_code"`

	// The currency code from ISO 4217 find more at https://en.wikipedia.org/wiki/ISO_4217
	CurrencyCode    CurrencyCode           `json:"currency_code"`
	MerchantCode    string                 `json:"merchant_code"`
	PosId           Id                     `json:"pos_id"`
	ProductId       Id                     `json:"product_id"`
	TransactionData TransactionDataRequest `json:"transaction_data"`
}

// RequestReversal defines model for request-reversal.
type RequestReversal struct {
	AcquirerCode      string `json:"acquirer_code"`
	AuthorizationCode string `json:"authorization_code"`

	// The country code from ISO 3166 find more at https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
	CountryCode CountryCode `json:"country_code"`

	// The currency code from ISO 4217 find more at https://en.wikipedia.org/wiki/ISO_4217
	CurrencyCode    CurrencyCode           `json:"currency_code"`
	MerchantCode    *string                `json:"merchant_code,omitempty"`
	PosId           Id                     `json:"pos_id"`
	ProductId       Id                     `json:"product_id"`
	TransactionData TransactionDataRequest `json:"transaction_data"`
}

// RequestTransaction defines model for request-transaction.
type RequestTransaction struct {
	AcquirerCode      string `json:"acquirer_code"`
	AuthorizationCode string `json:"authorization_code"`

	// The country code from ISO 3166 find more at https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
	CountryCode CountryCode `json:"country_code"`

	// The currency code from ISO 4217 find more at https://en.wikipedia.org/wiki/ISO_4217
	CurrencyCode    CurrencyCode           `json:"currency_code"`
	MerchantCode    string                 `json:"merchant_code"`
	PosId           Id                     `json:"pos_id"`
	ProductId       Id                     `json:"product_id"`
	TransactionData TransactionDataRequest `json:"transaction_data"`
}

// ResponseTransactions defines model for response-transactions.
type ResponseTransactions struct {
	RegisteredAt  *time.Time `json:"registered_at,omitempty"`
	TransactionId *string    `json:"transaction_id,omitempty"`
}

// TransactionDataRequest defines model for transaction-data-request.
type TransactionDataRequest struct {
	Amount        *float32                         `json:"amount,omitempty"`
	Operation     *TransactionDataRequestOperation `json:"operation,omitempty"`
	TransactionId *Id                              `json:"transaction_id,omitempty"`
	WithPassword  *bool                            `json:"with_password,omitempty"`
}

// TransactionDataRequestOperation defines model for TransactionDataRequest.Operation.
type TransactionDataRequestOperation string

// N201Success defines model for 201-success.
type N201Success = ResponseTransactions

// N400BadRequest defines model for 400-bad-request.
type N400BadRequest = GenericError

// N401Unauthorized defines model for 401-unauthorized.
type N401Unauthorized = GenericError

// N403Forbidden defines model for 403-forbidden.
type N403Forbidden = GenericError

// N500Unavailable defines model for 500-unavailable.
type N500Unavailable = GenericError

// CreateTransactionJSONBody defines parameters for CreateTransaction.
type CreateTransactionJSONBody = RequestTransaction

// RequestCancellationJSONBody defines parameters for RequestCancellation.
type RequestCancellationJSONBody = RequestCancellation

// RequestReversalJSONBody defines parameters for RequestReversal.
type RequestReversalJSONBody = RequestReversal

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = CreateTransactionJSONBody

// RequestCancellationJSONRequestBody defines body for RequestCancellation for application/json ContentType.
type RequestCancellationJSONRequestBody = RequestCancellationJSONBody

// RequestReversalJSONRequestBody defines body for RequestReversal for application/json ContentType.
type RequestReversalJSONRequestBody = RequestReversalJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /transactions)
	CreateTransaction(ctx echo.Context) error

	// (POST /transactions/{id}/cancellation)
	RequestCancellation(ctx echo.Context, id string) error

	// (POST /transactions/{id}/reversal)
	RequestReversal(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateTransaction converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTransaction(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateTransaction(ctx)
	return err
}

// RequestCancellation converts echo context to params.
func (w *ServerInterfaceWrapper) RequestCancellation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RequestCancellation(ctx, id)
	return err
}

// RequestReversal converts echo context to params.
func (w *ServerInterfaceWrapper) RequestReversal(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RequestReversal(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/transactions", wrapper.CreateTransaction)
	router.POST(baseURL+"/transactions/:id/cancellation", wrapper.RequestCancellation)
	router.POST(baseURL+"/transactions/:id/reversal", wrapper.RequestReversal)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZW2/bNhT+KxrXt4kxdbFk+y0thiJAgQ5p99RlBkUe2WwtUiXpppnh/z5QVmyJVpy0",
	"aPOw+U2Xcz/fd2QebxBTVa0kSGvQbIM0mFpJA81NTCJs1oyBaW6ZkhakdZe0rleCUSuUHH00Srpnhi2h",
	"ou7qhYYSzdCvo4Pt0e6tGd07wFZTaShzJgzabrch4mCYFrV7gmYIbUOUEoILyrGGz2sw9ocFsQAJWjAM",
	"Wiv9sPMIryVd26XS4h/gz+09waXSheAc5PO6HhPiEv9CxYoWK3hO59uwtdUCbi2tvpszxZso+tLvlxC0",
	"EoGTCEqtquDq3dsgibIsKIXkQaU0BNQGS2trMxuNQF7cik+iBi7ohdKLkbsbvRHGzlU5v3r3du50513H",
	"5i+JQgRfaVW7WqDL69coRBX9+gbkwi7RLAlRJWTnzt7VTtBYLeTCFZSttQbJTibSiniZpHGUf0smLgOn",
	"48X8+5/X3xpzv1mzzcGa64tLAxESIb+FjXhQgTF0Ac5OrVUN2gowB83NsbuelaP32xBZYZtU+nHtA1fF",
	"R2DWWRK8Fy1KWUGKbAoY0oLjNCszXJAowhPGxzzmyTRLC684Wb86WYhqai1ol+DfHwieUlzebCZbvL9O",
	"n3AdxdsXaKDS7XDDjEoGqxW9r0Gn4JR9XgsNugUQKvIsn9IJwYSRGEcRcDzJSYnzJJtmWTwZE6AoRPez",
	"qzHZ053mcV8XMCn4tKQ8yUiWo9DjHnp5fYmOgHyPK9BsSaXtR0cnPQ8RwVFCY0L4eEoSB5xamblrFqJx",
	"PAaep04+2clTIBHOEsIimhZxWTDUIImvmd3pND6KMev7yDAp8gmJ0jyLGHfFPnxk5pzaZkR1n3X8F6Tv",
	"P8Es4ZOSTHMWl2WDwT6WvaYMgHqo/gNi/pg7NUN7skOj5aRyT3h71LmB2O6bdNqw4C3V9w16ivxQc05p",
	"deSxk9//LNi2LBLafaU/HBsebEXoddAvh19cr1G9fPeFujlMqkFeDwysezkNX0Abujpz/8z9M/efm/se",
	"t33qP5Hrew6f4HknwjPVfx7VaeVSQ7M4iULkuNv+sEJMAxcWhehW2OW8psbcKs3RzOo1nJl+/sp/31e+",
	"y+pB8g+tPfr017AQxoIGPqcWzVBM4hiTHMfj9xGZpeksmvxGCCEe4FtyEZKRaUOUbEeUaUzGOE/KbEzG",
	"NC6S8fFxzPO4QaXSVeObUwvYigqGTiy+91PnteHEByr0YN+9GfkorY9qE+XxOJlCiqOUUpyShOBpHJWY",
	"QUnjeEKTHPgD4+BoGrTe9xnLdVWAdvF3YtkgkOvKYXQfFIdC2AY3jxfzcU55oe6jKZRaAZW9BjxY16Me",
	"OC0hS3W8obgMCk0lDyTcBpd/XAXOfyBV0K6FLoLgtQrk2ppf0MHxSyo/rVSAg8uWgE7Vtd59Ind2owty",
	"QdriSVoLNEPJBbmIUXPiXjYlH/mMqdUOFPuCX7kmv9JALbzvsbDN9KXidz9wf3nM921/NLXI8VepD1ne",
	"y426+9bd9vNxHX9FultcPkXP227udo7fpzh+SqT+WrEBKV0Yb5YbdOPe9No+2gi+HfkLkmEgXO8K8ap/",
	"6qqpphVY0M6dD++Oq0DwwKrA4eMuOFDaEQPNGlCiEElaOYA3X4R+28MOivyZePNzAdmrzv8Mkd1V+bPB",
	"sXtePwnF68Oh4L8Pw31VzhD8oRA8vDr6+6AjecCKOQCk/0/bzfbfAAAA//9Pz/hR9BsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
