apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "banklo-authorizer.fullname" . }}
spec:
  host: {{ include "banklo-authorizer.fullname" . }}
  subsets:
    - name: v1
      labels:
        version: v1