openapi: 3.0.2
info:
  title: Banklo - Acquirer APIs
  version: 1.0.0
  description: A brand new API with no content.  Go nuts!
paths:
  /transactions:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request-transaction'
        required: true
      tags:
        - transactions
      responses:
        '201':
          $ref: '#/components/responses/201-success'
        '400':
          $ref: '#/components/responses/400-bad-request'
        '401':
          $ref: '#/components/responses/401-unauthorized'
        '403':
          $ref: '#/components/responses/401-unauthorized'
        '500':
          $ref: '#/components/responses/500-unavailable'
      operationId: create-transaction
  '/transactions/{id}/cancellation':

    post:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: transaction id to apply operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request-cancellation'
        required: true
      tags:
        - transactions
      responses:
        '201':
          $ref: '#/components/responses/201-success'
        '400':
          $ref: '#/components/responses/400-bad-request'
        '401':
          $ref: '#/components/responses/401-unauthorized'
        '403':
          $ref: '#/components/responses/403-forbidden'
        '500':
          $ref: '#/components/responses/500-unavailable'
      operationId: request-cancellation
  '/transactions/{id}/reversal':
    post:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: transaction id to apply operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request-reversal'
        required: true
      tags:
        - transactions
      responses:
        '201':
          $ref: '#/components/responses/201-success'
        '400':
          $ref: '#/components/responses/400-bad-request'
        '401':
          $ref: '#/components/responses/401-unauthorized'
        '403':
          $ref: '#/components/responses/403-forbidden'
        '500':
          $ref: '#/components/responses/500-unavailable'
      operationId: request-reversal
components:
  schemas:
    request-transaction:
      title: Root Type for request-transaction
      description: ''
      type: object
      properties:
        authorization_code:
          type: string
        acquirer_code:
          type: string
        merchant_code:
          type: string
        currency_code:
          type: string
        transaction_data:
          type: object
          properties:
            with_password:
              type: boolean
            transaction_type:
              type: string
            amount:
              format: int32
              type: integer
        country_code:
          type: string
        product_id:
          type: string
        pos_id:
          type: string
      example:
        authorization_code: b7679972-0c02-11ed-870e-0bd9fad36067
        acquirer_code: b7679a80-0c02-11ed-870f-7369662850ea
        merchant_code: b7679aa8-0c02-11ed-8710-13a200d59031
        currency_code: b7679b02-0c02-11ed-8713-0f4e1eec6501
        transaction_data:
          with_password: true
          transaction_type: credit
          amount: 231
        country_code: BRA
        product_id: b7679b5c-0c02-11ed-8716-0b78014761cd
        pos_id: a225ed74-0c03-11ed-ae01-630c1a4b2fbc
    request-reversal:
      title: Root Type for request-reversal
      description: ''
      type: object
      properties:
        authorization_code:
          type: string
        acquirer_code:
          type: string
        merchant_code:
          type: string
        currency_code:
          type: string
        transaction_data:
          type: object
          properties:
            transaction_type:
              type: string
            transaction_id:
              type: string
        country_code:
          type: string
        product_id:
          type: string
        pos_id:
          type: string
      example:
        authorization_code: b7679972-0c02-11ed-870e-0bd9fad36067
        acquirer_code: b7679a80-0c02-11ed-870f-7369662850ea
        merchant_code: b7679aa8-0c02-11ed-8710-13a200d59031
        currency_code: b7679b02-0c02-11ed-8713-0f4e1eec6501
        transaction_data:
          transaction_type: reversal
          transaction_id: a225edb0-0c03-11ed-ae03-c3d8f097c2ff
        country_code: BRA
        product_id: b7679b5c-0c02-11ed-8716-0b78014761cd
        pos_id: a225ed74-0c03-11ed-ae01-630c1a4b2fbc
    request-cancellation:
      title: Root Type for request-cancellation
      description: ''
      type: object
      properties:
        authorization_code:
          type: string
        acquirer_code:
          type: string
        merchant_code:
          type: string
        currency_code:
          type: string
        transaction_data:
          type: object
          properties:
            transaction_type:
              type: string
            transaction_id:
              type: string
        country_code:
          type: string
        product_id:
          type: string
        pos_id:
          type: string
      example:
        authorization_code: b7679972-0c02-11ed-870e-0bd9fad36067
        acquirer_code: b7679a80-0c02-11ed-870f-7369662850ea
        merchant_code: b7679aa8-0c02-11ed-8710-13a200d59031
        currency_code: b7679b02-0c02-11ed-8713-0f4e1eec6501
        transaction_data:
          transaction_type: cancellation
          transaction_id: a225edb0-0c03-11ed-ae03-c3d8f097c2ff
        country_code: BRA
        product_id: b7679b5c-0c02-11ed-8716-0b78014761cd
        pos_id: a225ed74-0c03-11ed-ae01-630c1a4b2fbc
    response-transactions:
      title: Root Type for response-transactions
      description: ''
      type: object
      properties:
        transaction_id:
          type: string
        registered_at:
          format: date-time
          type: string
      example:
        transaction_id: a200609c-0c06-11ed-9205-73f6505a2b35
        registered_at: '2022-07-25T10:44:18+0000'
    generic-error:
      title: Root Type for generic-error
      description: ''
      type: object
      properties:
        code:
          type: string
        description:
          type: string
      example:
        code: '001'
        description: error message
  responses:
    201-success:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/response-transactions'
      description: ''
    400-bad-request:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic-error'
      description: ''
    401-unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic-error'
      description: ''
    403-forbidden:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic-error'
      description: ''
    500-unavailable:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic-error'
      description: ''
tags:
  -
    name: transactions
    description: Transactions operations